const TRANSPARENT_IMAGE_DATA_URL =
  "data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///ywAAAAAAQABAAACAUwAOw==";

export const TCOIN_BANNER_LIGHT_URL =
  process.env.NEXT_PUBLIC_TCOIN_BANNER_LIGHT_URL?.trim() || TRANSPARENT_IMAGE_DATA_URL;

export const TCOIN_BANNER_DARK_URL =
  process.env.NEXT_PUBLIC_TCOIN_BANNER_DARK_URL?.trim() || TRANSPARENT_IMAGE_DATA_URL;

export const TCOIN_WELCOME_VIDEO_URL = process.env.NEXT_PUBLIC_TCOIN_WELCOME_VIDEO_URL?.trim() || "";
