export const orchestratorV2Abi = [
  {
    type: "function",
    name: "owner",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
  },
  {
    type: "function",
    name: "isSteward",
    stateMutability: "view",
    inputs: [{ name: "addr", type: "address" }],
    outputs: [{ name: "", type: "bool" }],
  },
  {
    type: "function",
    name: "isCharity",
    stateMutability: "view",
    inputs: [{ name: "charity", type: "address" }],
    outputs: [{ name: "", type: "bool" }],
  },
  {
    type: "function",
    name: "getStewardCount",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "nominateSteward",
    stateMutability: "nonpayable",
    inputs: [
      { name: "stewardId", type: "uint256" },
      { name: "name", type: "string" },
      { name: "stewardAddress", type: "address" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "rebaseTCOIN",
    stateMutability: "nonpayable",
    inputs: [],
    outputs: [],
  },
  {
    type: "function",
    name: "updateDemurrageRate",
    stateMutability: "nonpayable",
    inputs: [{ name: "newDemurrageRate", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "updateRebasePeriod",
    stateMutability: "nonpayable",
    inputs: [{ name: "newRebasePeriod", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "whitelistStore",
    stateMutability: "nonpayable",
    inputs: [{ name: "store", type: "address" }],
    outputs: [],
  },
  {
    type: "function",
    name: "removeStoreFromWhitelist",
    stateMutability: "nonpayable",
    inputs: [{ name: "store", type: "address" }],
    outputs: [],
  },
  {
    type: "function",
    name: "mintTCOINForCharity",
    stateMutability: "nonpayable",
    inputs: [{ name: "tcoinAmount", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "applyGovernanceValues",
    stateMutability: "nonpayable",
    inputs: [
      { name: "pegValue_", type: "uint256" },
      { name: "redemptionRateUserTTC_", type: "uint256" },
      { name: "redemptionRateStoreTTC_", type: "uint256" },
      { name: "redemptionRateUserCAD_", type: "uint256" },
      { name: "redemptionRateStoreCAD_", type: "uint256" },
      { name: "minimumReserveRatio_", type: "uint256" },
      { name: "maximumReserveRatio_", type: "uint256" },
      { name: "demurrageRate_", type: "uint256" },
      { name: "reserveRatio_", type: "uint256" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "addReserveCurrency",
    stateMutability: "nonpayable",
    inputs: [
      { name: "code", type: "bytes32" },
      { name: "token", type: "address" },
      { name: "decimals", type: "uint8" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "disableReserveCurrency",
    stateMutability: "nonpayable",
    inputs: [{ name: "code", type: "bytes32" }],
    outputs: [],
  },
  {
    type: "function",
    name: "enableReserveCurrency",
    stateMutability: "nonpayable",
    inputs: [{ name: "code", type: "bytes32" }],
    outputs: [],
  },
  {
    type: "function",
    name: "getReserveCurrency",
    stateMutability: "view",
    inputs: [{ name: "code", type: "bytes32" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        components: [
          { name: "code", type: "bytes32" },
          { name: "token", type: "address" },
          { name: "decimals", type: "uint8" },
          { name: "enabled", type: "bool" },
        ],
      },
    ],
  },
  {
    type: "function",
    name: "listReserveCurrencies",
    stateMutability: "view",
    inputs: [],
    outputs: [
      {
        name: "list",
        type: "tuple[]",
        components: [
          { name: "code", type: "bytes32" },
          { name: "token", type: "address" },
          { name: "decimals", type: "uint8" },
          { name: "enabled", type: "bool" },
        ],
      },
    ],
  },
] as const;
