export const votingV2Abi = [
  {
    type: "function",
    name: "owner",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
  },
  {
    type: "function",
    name: "proposePegValue",
    stateMutability: "nonpayable",
    inputs: [
      { name: "proposedPegValue", type: "uint256" },
      { name: "votingWindow", type: "uint64" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "votePegValue",
    stateMutability: "nonpayable",
    inputs: [{ name: "proposedPegValue", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "proposeCharity",
    stateMutability: "nonpayable",
    inputs: [
      { name: "charityId", type: "uint256" },
      { name: "name", type: "string" },
      { name: "wallet", type: "address" },
      { name: "metadataRecordId", type: "string" },
      { name: "votingWindow", type: "uint64" },
    ],
    outputs: [{ name: "proposalId", type: "uint256" }],
  },
  {
    type: "function",
    name: "proposeReserveCurrency",
    stateMutability: "nonpayable",
    inputs: [
      { name: "code", type: "bytes32" },
      { name: "token", type: "address" },
      { name: "decimals", type: "uint8" },
      { name: "metadataRecordId", type: "string" },
      { name: "votingWindow", type: "uint64" },
    ],
    outputs: [{ name: "proposalId", type: "uint256" }],
  },
  {
    type: "function",
    name: "voteProposal",
    stateMutability: "nonpayable",
    inputs: [
      { name: "proposalId", type: "uint256" },
      { name: "support", type: "bool" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "executeProposal",
    stateMutability: "nonpayable",
    inputs: [{ name: "proposalId", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "cancelProposal",
    stateMutability: "nonpayable",
    inputs: [{ name: "proposalId", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "proposalCount",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "getPegValue",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "getProposal",
    stateMutability: "view",
    inputs: [{ name: "proposalId", type: "uint256" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        components: [
          { name: "proposalId", type: "uint256" },
          { name: "proposalType", type: "uint8" },
          { name: "cityId", type: "bytes32" },
          { name: "charityId", type: "uint256" },
          { name: "name", type: "string" },
          { name: "wallet", type: "address" },
          { name: "code", type: "bytes32" },
          { name: "token", type: "address" },
          { name: "decimals", type: "uint8" },
          { name: "metadataRecordId", type: "string" },
          { name: "yesVotes", type: "uint256" },
          { name: "noVotes", type: "uint256" },
          { name: "deadline", type: "uint64" },
          { name: "status", type: "uint8" },
          { name: "proposer", type: "address" },
        ],
      },
    ],
  },
  {
    type: "function",
    name: "listProposalIdsByStatus",
    stateMutability: "view",
    inputs: [
      { name: "status", type: "uint8" },
      { name: "cursor", type: "uint256" },
      { name: "size", type: "uint256" },
    ],
    outputs: [
      { name: "ids", type: "uint256[]" },
      { name: "nextCursor", type: "uint256" },
    ],
  },
] as const;
