-- migrate:up
BEGIN;

CREATE TABLE IF NOT EXISTS public.wallet_keys (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  namespace public.namespace NOT NULL DEFAULT 'EVM'::public.namespace,
  app_share text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT wallet_keys_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE
);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'wallet_keys_user_id_namespace_key'
      AND conrelid = 'public.wallet_keys'::regclass
  ) THEN
    ALTER TABLE public.wallet_keys
      ADD CONSTRAINT wallet_keys_user_id_namespace_key UNIQUE (user_id, namespace);
  END IF;
END
$$;

ALTER TABLE IF EXISTS public.wallet_list
  ADD COLUMN IF NOT EXISTS wallet_key_id bigint;

ALTER TABLE IF EXISTS public.user_encrypted_share
  ADD COLUMN IF NOT EXISTS wallet_key_id bigint;

INSERT INTO public.wallet_keys (user_id, namespace, app_share)
SELECT
  u.id,
  COALESCE(seed.namespace, 'EVM'::public.namespace) AS namespace,
  seed.app_share
FROM public.users AS u
LEFT JOIN LATERAL (
  SELECT wl.namespace, wl.app_share
  FROM public.wallet_list AS wl
  WHERE wl.user_id = u.id
  ORDER BY wl.id ASC
  LIMIT 1
) AS seed ON TRUE
ON CONFLICT (user_id, namespace)
DO UPDATE SET
  app_share = COALESCE(public.wallet_keys.app_share, EXCLUDED.app_share),
  updated_at = now();

UPDATE public.wallet_list AS wl
SET
  wallet_key_id = wk.id
FROM public.wallet_keys AS wk
WHERE wl.user_id = wk.user_id
  AND wl.namespace = wk.namespace
  AND wl.wallet_key_id IS DISTINCT FROM wk.id;

UPDATE public.user_encrypted_share AS ues
SET wallet_key_id = wk.id
FROM public.wallet_keys AS wk
WHERE ues.user_id = wk.user_id
  AND wk.namespace = 'EVM'::public.namespace
  AND ues.wallet_key_id IS DISTINCT FROM wk.id;

DO $$
DECLARE
  remaining_wallet_list bigint;
  remaining_user_share bigint;
BEGIN
  SELECT COUNT(*) INTO remaining_wallet_list
  FROM public.wallet_list
  WHERE user_id IS NOT NULL
    AND wallet_key_id IS NULL;

  IF remaining_wallet_list > 0 THEN
    RAISE EXCEPTION 'wallet_list backfill incomplete: % rows still missing wallet_key_id', remaining_wallet_list;
  END IF;

  SELECT COUNT(*) INTO remaining_user_share
  FROM public.user_encrypted_share
  WHERE user_id IS NOT NULL
    AND wallet_key_id IS NULL;

  IF remaining_user_share > 0 THEN
    RAISE EXCEPTION 'user_encrypted_share backfill incomplete: % rows still missing wallet_key_id', remaining_user_share;
  END IF;
END
$$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'wallet_list_wallet_key_id_for_user_chk'
      AND conrelid = 'public.wallet_list'::regclass
  ) THEN
    ALTER TABLE public.wallet_list
      ADD CONSTRAINT wallet_list_wallet_key_id_for_user_chk
      CHECK (user_id IS NULL OR wallet_key_id IS NOT NULL);
  END IF;
END
$$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'wallet_list_wallet_key_id_fkey'
      AND conrelid = 'public.wallet_list'::regclass
  ) THEN
    ALTER TABLE public.wallet_list
      ADD CONSTRAINT wallet_list_wallet_key_id_fkey
      FOREIGN KEY (wallet_key_id)
      REFERENCES public.wallet_keys(id)
      ON DELETE RESTRICT;
  END IF;
END
$$;

DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'wallet_list'
      AND column_name = 'app_share'
  ) THEN
    ALTER TABLE public.wallet_list
      DROP COLUMN app_share;
  END IF;
END
$$;

ALTER TABLE IF EXISTS public.user_encrypted_share
  ALTER COLUMN wallet_key_id SET NOT NULL;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'user_encrypted_share_wallet_key_id_fkey'
      AND conrelid = 'public.user_encrypted_share'::regclass
  ) THEN
    ALTER TABLE public.user_encrypted_share
      ADD CONSTRAINT user_encrypted_share_wallet_key_id_fkey
      FOREIGN KEY (wallet_key_id)
      REFERENCES public.wallet_keys(id)
      ON DELETE RESTRICT;
  END IF;
END
$$;

COMMIT;

-- migrate:down
BEGIN;

ALTER TABLE IF EXISTS public.wallet_list
  ADD COLUMN IF NOT EXISTS app_share text;

UPDATE public.wallet_list AS wl
SET app_share = wk.app_share
FROM public.wallet_keys AS wk
WHERE wl.wallet_key_id = wk.id
  AND wl.app_share IS DISTINCT FROM wk.app_share;

ALTER TABLE IF EXISTS public.user_encrypted_share
  DROP CONSTRAINT IF EXISTS user_encrypted_share_wallet_key_id_fkey;

ALTER TABLE IF EXISTS public.user_encrypted_share
  ALTER COLUMN wallet_key_id DROP NOT NULL;

ALTER TABLE IF EXISTS public.user_encrypted_share
  DROP COLUMN IF EXISTS wallet_key_id;

ALTER TABLE IF EXISTS public.wallet_list
  DROP CONSTRAINT IF EXISTS wallet_list_wallet_key_id_fkey;

ALTER TABLE IF EXISTS public.wallet_list
  DROP CONSTRAINT IF EXISTS wallet_list_wallet_key_id_for_user_chk;

ALTER TABLE IF EXISTS public.wallet_list
  DROP COLUMN IF EXISTS wallet_key_id;

DROP TABLE IF EXISTS public.wallet_keys;

COMMIT;
