BEGIN;

CREATE TABLE IF NOT EXISTS public.payment_request_links (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  token_hash text NOT NULL,
  app_instance_id bigint NOT NULL REFERENCES public.ref_app_instances(id) ON DELETE CASCADE,
  recipient_user_id bigint NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  amount_requested numeric NULL,
  mode text NOT NULL DEFAULT 'rotating_multi_use',
  expires_at timestamptz NOT NULL,
  consumed_at timestamptz NULL,
  consumed_by_user_id bigint NULL REFERENCES public.users(id) ON DELETE SET NULL,
  consumed_transaction_id bigint NULL,
  created_at timestamptz NOT NULL DEFAULT timezone('utc', now()),
  updated_at timestamptz NOT NULL DEFAULT timezone('utc', now()),
  CONSTRAINT payment_request_links_token_hash_key UNIQUE (token_hash),
  CONSTRAINT payment_request_links_mode_check CHECK (mode IN ('rotating_multi_use', 'single_use')),
  CONSTRAINT payment_request_links_amount_check CHECK (amount_requested IS NULL OR amount_requested >= 0)
);

CREATE INDEX IF NOT EXISTS payment_request_links_recipient_idx
  ON public.payment_request_links (recipient_user_id, app_instance_id, created_at DESC);

CREATE INDEX IF NOT EXISTS payment_request_links_expiry_idx
  ON public.payment_request_links (expires_at DESC, consumed_at);

COMMIT;

-- DOWN
-- BEGIN;
-- DROP INDEX IF EXISTS public.payment_request_links_expiry_idx;
-- DROP INDEX IF EXISTS public.payment_request_links_recipient_idx;
-- DROP TABLE IF EXISTS public.payment_request_links;
-- COMMIT;
