-- migrate:up
BEGIN;

CREATE TABLE IF NOT EXISTS public.user_contact_import_preferences (
  user_id bigint NOT NULL,
  app_instance_id bigint NOT NULL,
  granted boolean NOT NULL DEFAULT false,
  source text NOT NULL DEFAULT 'browser-contact-picker',
  created_at timestamptz NOT NULL DEFAULT timezone('utc', now()),
  updated_at timestamptz NOT NULL DEFAULT timezone('utc', now()),
  CONSTRAINT user_contact_import_preferences_pkey PRIMARY KEY (user_id, app_instance_id),
  CONSTRAINT user_contact_import_preferences_user_fkey
    FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE,
  CONSTRAINT user_contact_import_preferences_app_instance_fkey
    FOREIGN KEY (app_instance_id) REFERENCES public.ref_app_instances(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.user_imported_contacts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  app_instance_id bigint NOT NULL,
  display_name text,
  email text NOT NULL,
  source text NOT NULL DEFAULT 'browser-contact-picker',
  created_at timestamptz NOT NULL DEFAULT timezone('utc', now()),
  updated_at timestamptz NOT NULL DEFAULT timezone('utc', now()),
  CONSTRAINT user_imported_contacts_user_fkey
    FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE,
  CONSTRAINT user_imported_contacts_app_instance_fkey
    FOREIGN KEY (app_instance_id) REFERENCES public.ref_app_instances(id) ON DELETE CASCADE
);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'user_imported_contacts_user_app_email_key'
      AND conrelid = 'public.user_imported_contacts'::regclass
  ) THEN
    ALTER TABLE public.user_imported_contacts
      ADD CONSTRAINT user_imported_contacts_user_app_email_key
      UNIQUE (user_id, app_instance_id, email);
  END IF;
END
$$;

CREATE INDEX IF NOT EXISTS user_imported_contacts_lookup_idx
  ON public.user_imported_contacts (user_id, app_instance_id, updated_at DESC);

CREATE TABLE IF NOT EXISTS public.contact_invite_batches (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL,
  app_instance_id bigint NOT NULL,
  source text NOT NULL DEFAULT 'manual',
  subject text NOT NULL,
  message text NOT NULL,
  status text NOT NULL DEFAULT 'queued',
  created_at timestamptz NOT NULL DEFAULT timezone('utc', now()),
  updated_at timestamptz NOT NULL DEFAULT timezone('utc', now()),
  CONSTRAINT contact_invite_batches_user_fkey
    FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE,
  CONSTRAINT contact_invite_batches_app_instance_fkey
    FOREIGN KEY (app_instance_id) REFERENCES public.ref_app_instances(id) ON DELETE CASCADE
);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'contact_invite_batches_status_check'
      AND conrelid = 'public.contact_invite_batches'::regclass
  ) THEN
    ALTER TABLE public.contact_invite_batches
      ADD CONSTRAINT contact_invite_batches_status_check
      CHECK (status IN ('queued', 'processing', 'sent', 'cancelled'));
  END IF;
END
$$;

CREATE INDEX IF NOT EXISTS contact_invite_batches_lookup_idx
  ON public.contact_invite_batches (user_id, app_instance_id, created_at DESC);

CREATE TABLE IF NOT EXISTS public.contact_invite_batch_recipients (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  batch_id bigint NOT NULL,
  email text NOT NULL,
  display_name text,
  source text NOT NULL DEFAULT 'manual',
  created_at timestamptz NOT NULL DEFAULT timezone('utc', now()),
  CONSTRAINT contact_invite_batch_recipients_batch_fkey
    FOREIGN KEY (batch_id) REFERENCES public.contact_invite_batches(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS contact_invite_batch_recipients_batch_idx
  ON public.contact_invite_batch_recipients (batch_id, email);

COMMIT;

-- DOWN
-- BEGIN;
-- DROP INDEX IF EXISTS contact_invite_batch_recipients_batch_idx;
-- DROP TABLE IF EXISTS public.contact_invite_batch_recipients;
-- DROP INDEX IF EXISTS contact_invite_batches_lookup_idx;
-- ALTER TABLE IF EXISTS public.contact_invite_batches
--   DROP CONSTRAINT IF EXISTS contact_invite_batches_status_check;
-- DROP TABLE IF EXISTS public.contact_invite_batches;
-- DROP INDEX IF EXISTS user_imported_contacts_lookup_idx;
-- ALTER TABLE IF EXISTS public.user_imported_contacts
--   DROP CONSTRAINT IF EXISTS user_imported_contacts_user_app_email_key;
-- DROP TABLE IF EXISTS public.user_imported_contacts;
-- DROP TABLE IF EXISTS public.user_contact_import_preferences;
-- COMMIT;
