-- v0.66: legacy baseline bootstrap for clean-slate environments.
-- This migration makes the existing ALTER-based migrations runnable from an empty DB.

BEGIN;

CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_type t
    JOIN pg_namespace n ON n.oid = t.typnamespace
    WHERE n.nspname = 'public'
      AND t.typname = 'namespace'
  ) THEN
    CREATE TYPE public.namespace AS ENUM ('EVM');
  END IF;
END
$$;

ALTER TYPE public.namespace ADD VALUE IF NOT EXISTS 'EVM';

CREATE TABLE IF NOT EXISTS public.ref_personas (
  persona text PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS public.users (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cubid_id text,
  username text,
  email text,
  phone text,
  full_name text,
  address text,
  bio text,
  profile_image_url text,
  has_completed_intro boolean DEFAULT false,
  is_new_user boolean,
  is_admin boolean DEFAULT false,
  auth_user_id text,
  cubid_score jsonb,
  cubid_identity jsonb,
  cubid_score_details jsonb,
  user_identifier text,
  given_names text,
  family_name text,
  nickname text,
  country text,
  persona text,
  preferred_donation_amount numeric,
  selected_cause text,
  good_tip smallint,
  default_tip smallint,
  current_step smallint,
  category text,
  charity text,
  style smallint,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'users_persona_fkey'
      AND conrelid = 'public.users'::regclass
  ) THEN
    ALTER TABLE public.users
      ADD CONSTRAINT users_persona_fkey
      FOREIGN KEY (persona) REFERENCES public.ref_personas(persona);
  END IF;
END
$$;

CREATE TABLE IF NOT EXISTS public.ref_apps (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug text NOT NULL UNIQUE,
  name text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.ref_citycoins (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug text NOT NULL UNIQUE,
  display_name text NOT NULL,
  symbol text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.ref_app_instances (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug text NOT NULL UNIQUE,
  app_id bigint NOT NULL REFERENCES public.ref_apps(id) ON DELETE CASCADE,
  citycoin_id bigint NOT NULL REFERENCES public.ref_citycoins(id) ON DELETE CASCADE,
  environment text NOT NULL DEFAULT 'development',
  site_url text,
  supabase_project_ref text,
  supabase_url text,
  notes text,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT ref_app_instances_app_city_env_key UNIQUE (app_id, citycoin_id, environment)
);

INSERT INTO public.ref_apps (id, slug, name)
VALUES
  (1, 'wallet', 'Wallet'),
  (2, 'sparechange', 'Spare Change')
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.ref_apps (slug, name)
VALUES
  ('wallet', 'Wallet'),
  ('sparechange', 'Spare Change')
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.ref_citycoins (id, slug, display_name, symbol)
VALUES (1, 'tcoin', 'Toronto Coin', 'TCOIN')
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.ref_citycoins (slug, display_name, symbol)
VALUES ('tcoin', 'Toronto Coin', 'TCOIN')
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.ref_app_instances (id, slug, app_id, citycoin_id, environment, site_url)
VALUES (3, 'wallet-tcoin-development', 1, 1, 'development', 'http://localhost:3000')
ON CONFLICT (id) DO NOTHING;

SELECT setval(
  pg_get_serial_sequence('public.ref_app_instances', 'id'),
  GREATEST((SELECT COALESCE(MAX(id), 0) FROM public.ref_app_instances), 3),
  true
);

CREATE TABLE IF NOT EXISTS public.interac_transfer (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.off_ramp_req (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.act_transactions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_by bigint,
  onramp_request_id bigint,
  offramp_request_id bigint,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.notifications (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint,
  trx_entry_id bigint,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.app_admin_notifications (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.stores (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.store_employees (
  store_id bigint NOT NULL,
  user_id bigint NOT NULL,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.invoice_pay_request (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  transaction_id bigint,
  request_from bigint,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.connections (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_user_id bigint,
  connected_user_id bigint,
  state text,
  created_at timestamptz DEFAULT now(),
  modified_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.invites (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  token text,
  from_user_id bigint,
  used_by_user_id bigint,
  expires_at timestamptz,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.roles (
  user_id bigint,
  role text,
  assigned_by bigint,
  sequential_id bigint GENERATED BY DEFAULT AS IDENTITY,
  created_at timestamptz DEFAULT now(),
  CONSTRAINT roles_id_key UNIQUE (sequential_id)
);

CREATE TABLE IF NOT EXISTS public.user_requests (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text,
  email text,
  message text,
  ip_addresses text[] DEFAULT '{}'::text[],
  created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.wallet_list (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint,
  namespace public.namespace NOT NULL DEFAULT 'EVM'::public.namespace,
  app_share text
);

CREATE TABLE IF NOT EXISTS public.user_encrypted_share (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint,
  namespace public.namespace NOT NULL DEFAULT 'EVM'::public.namespace,
  encrypted_share text
);

COMMIT;
