-- v1.08: track multiple user emails with soft-delete history and an active primary email.

BEGIN;

CREATE TABLE IF NOT EXISTS public.user_email_addresses (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  email text NOT NULL,
  is_primary boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz
);

ALTER TABLE public.user_email_addresses
  ADD COLUMN IF NOT EXISTS user_id bigint,
  ADD COLUMN IF NOT EXISTS email text,
  ADD COLUMN IF NOT EXISTS is_primary boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS created_at timestamptz DEFAULT now(),
  ADD COLUMN IF NOT EXISTS updated_at timestamptz DEFAULT now(),
  ADD COLUMN IF NOT EXISTS deleted_at timestamptz;

UPDATE public.user_email_addresses
SET
  email = lower(btrim(email)),
  updated_at = COALESCE(updated_at, now()),
  created_at = COALESCE(created_at, now()),
  is_primary = COALESCE(is_primary, false)
WHERE email IS NOT NULL
  AND (
    email <> lower(btrim(email))
    OR updated_at IS NULL
    OR created_at IS NULL
    OR is_primary IS NULL
  );

CREATE UNIQUE INDEX IF NOT EXISTS user_email_addresses_active_email_key
  ON public.user_email_addresses ((lower(email)))
  WHERE deleted_at IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS user_email_addresses_active_primary_per_user_key
  ON public.user_email_addresses (user_id)
  WHERE deleted_at IS NULL AND is_primary = true;

CREATE INDEX IF NOT EXISTS user_email_addresses_active_user_id_idx
  ON public.user_email_addresses (user_id, created_at)
  WHERE deleted_at IS NULL;

INSERT INTO public.user_email_addresses (user_id, email, is_primary, created_at, updated_at)
SELECT
  u.id,
  lower(btrim(u.email)),
  true,
  COALESCE(u.created_at, now()),
  COALESCE(u.updated_at, COALESCE(u.created_at, now()))
FROM public.users u
WHERE u.email IS NOT NULL
  AND btrim(u.email) <> ''
  AND NOT EXISTS (
    SELECT 1
    FROM public.user_email_addresses ue
    WHERE ue.user_id = u.id
      AND lower(ue.email) = lower(btrim(u.email))
      AND ue.deleted_at IS NULL
  );

CREATE OR REPLACE FUNCTION public.sync_users_primary_email_from_history()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
  target_user_id bigint;
BEGIN
  target_user_id := COALESCE(NEW.user_id, OLD.user_id);

  UPDATE public.users u
  SET
    email = next_email.email,
    updated_at = now()
  FROM (
    SELECT ue.email
    FROM public.user_email_addresses ue
    WHERE ue.user_id = target_user_id
      AND ue.deleted_at IS NULL
    ORDER BY ue.is_primary DESC, ue.created_at ASC, ue.id ASC
    LIMIT 1
  ) AS next_email
  WHERE u.id = target_user_id
    AND u.email IS DISTINCT FROM next_email.email;

  UPDATE public.users
  SET
    email = NULL,
    updated_at = now()
  WHERE id = target_user_id
    AND NOT EXISTS (
      SELECT 1
      FROM public.user_email_addresses ue
      WHERE ue.user_id = target_user_id
        AND ue.deleted_at IS NULL
    )
    AND email IS NOT NULL;

  RETURN COALESCE(NEW, OLD);
END;
$$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_trigger
    WHERE tgname = 'sync_users_primary_email_from_history_trigger'
      AND tgrelid = 'public.user_email_addresses'::regclass
  ) THEN
    CREATE TRIGGER sync_users_primary_email_from_history_trigger
    AFTER INSERT OR UPDATE OR DELETE ON public.user_email_addresses
    FOR EACH ROW
    EXECUTE FUNCTION public.sync_users_primary_email_from_history();
  END IF;
END
$$;

UPDATE public.users u
SET
  email = next_email.email,
  updated_at = now()
FROM (
  SELECT DISTINCT ON (ue.user_id)
    ue.user_id,
    ue.email
  FROM public.user_email_addresses ue
  WHERE ue.deleted_at IS NULL
  ORDER BY ue.user_id, ue.is_primary DESC, ue.created_at ASC, ue.id ASC
) AS next_email
WHERE u.id = next_email.user_id
  AND u.email IS DISTINCT FROM next_email.email;

COMMIT;

-- DOWN
-- BEGIN;
-- DROP TRIGGER IF EXISTS sync_users_primary_email_from_history_trigger ON public.user_email_addresses;
-- DROP FUNCTION IF EXISTS public.sync_users_primary_email_from_history();
-- DROP INDEX IF EXISTS public.user_email_addresses_active_user_id_idx;
-- DROP INDEX IF EXISTS public.user_email_addresses_active_primary_per_user_key;
-- DROP INDEX IF EXISTS public.user_email_addresses_active_email_key;
-- DROP TABLE IF EXISTS public.user_email_addresses;
-- COMMIT;
