-- v1.08: track multiple user emails with soft-delete history and an active primary email.

BEGIN;

CREATE TABLE IF NOT EXISTS public.user_email_addresses (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  email text NOT NULL,
  is_primary boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz
);

ALTER TABLE public.user_email_addresses
  ADD COLUMN IF NOT EXISTS user_id bigint,
  ADD COLUMN IF NOT EXISTS email text,
  ADD COLUMN IF NOT EXISTS is_primary boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS created_at timestamptz DEFAULT now(),
  ADD COLUMN IF NOT EXISTS updated_at timestamptz DEFAULT now(),
  ADD COLUMN IF NOT EXISTS deleted_at timestamptz;

UPDATE public.user_email_addresses
SET
  email = lower(btrim(email)),
  updated_at = COALESCE(updated_at, now()),
  created_at = COALESCE(created_at, now()),
  is_primary = COALESCE(is_primary, false)
WHERE email IS NOT NULL
  AND (
    email <> lower(btrim(email))
    OR updated_at IS NULL
    OR created_at IS NULL
    OR is_primary IS NULL
  );

WITH ranked_existing_emails AS (
  SELECT
    ue.id,
    row_number() OVER (
      PARTITION BY lower(ue.email)
      ORDER BY
        ue.is_primary DESC,
        COALESCE(ue.updated_at, ue.created_at, now()) DESC,
        COALESCE(ue.created_at, now()) ASC,
        ue.id ASC
    ) AS email_rank
  FROM public.user_email_addresses ue
  WHERE ue.deleted_at IS NULL
    AND ue.email IS NOT NULL
    AND btrim(ue.email) <> ''
)
UPDATE public.user_email_addresses ue
SET
  deleted_at = COALESCE(ue.deleted_at, now()),
  is_primary = false,
  updated_at = now()
FROM ranked_existing_emails ranked
WHERE ue.id = ranked.id
  AND ranked.email_rank > 1;

WITH ranked_existing_primaries AS (
  SELECT
    ue.id,
    row_number() OVER (
      PARTITION BY ue.user_id
      ORDER BY
        ue.is_primary DESC,
        COALESCE(ue.updated_at, ue.created_at, now()) DESC,
        COALESCE(ue.created_at, now()) ASC,
        ue.id ASC
    ) AS primary_rank
  FROM public.user_email_addresses ue
  WHERE ue.deleted_at IS NULL
)
UPDATE public.user_email_addresses ue
SET
  is_primary = CASE WHEN ranked.primary_rank = 1 THEN ue.is_primary ELSE false END,
  updated_at = now()
FROM ranked_existing_primaries ranked
WHERE ue.id = ranked.id
  AND ue.is_primary = true
  AND ranked.primary_rank > 1;

CREATE UNIQUE INDEX IF NOT EXISTS user_email_addresses_active_email_key
  ON public.user_email_addresses ((lower(email)))
  WHERE deleted_at IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS user_email_addresses_active_primary_per_user_key
  ON public.user_email_addresses (user_id)
  WHERE deleted_at IS NULL AND is_primary = true;

CREATE INDEX IF NOT EXISTS user_email_addresses_active_user_id_idx
  ON public.user_email_addresses (user_id, created_at)
  WHERE deleted_at IS NULL;

WITH normalized_users AS (
  SELECT
    u.id AS user_id,
    lower(btrim(u.email)) AS normalized_email,
    u.auth_user_id,
    COALESCE(u.created_at, now()) AS created_at,
    COALESCE(u.updated_at, COALESCE(u.created_at, now())) AS updated_at
  FROM public.users u
  WHERE u.email IS NOT NULL
    AND btrim(u.email) <> ''
), ranked_users AS (
  SELECT
    normalized_users.*,
    row_number() OVER (
      PARTITION BY normalized_users.normalized_email
      ORDER BY
        CASE WHEN normalized_users.auth_user_id IS NOT NULL THEN 0 ELSE 1 END,
        normalized_users.updated_at DESC,
        normalized_users.created_at ASC,
        normalized_users.user_id ASC
    ) AS email_rank
  FROM normalized_users
)
INSERT INTO public.user_email_addresses (user_id, email, is_primary, created_at, updated_at)
SELECT
  ranked.user_id,
  ranked.normalized_email,
  NOT EXISTS (
    SELECT 1
    FROM public.user_email_addresses ue_existing_user
    WHERE ue_existing_user.user_id = ranked.user_id
      AND ue_existing_user.deleted_at IS NULL
  ),
  ranked.created_at,
  ranked.updated_at
FROM ranked_users ranked
WHERE ranked.email_rank = 1
  AND NOT EXISTS (
    SELECT 1
    FROM public.user_email_addresses ue
    WHERE lower(ue.email) = ranked.normalized_email
      AND ue.deleted_at IS NULL
  )
  AND NOT EXISTS (
    SELECT 1
    FROM public.user_email_addresses ue
    WHERE ue.user_id = ranked.user_id
      AND lower(ue.email) = ranked.normalized_email
      AND ue.deleted_at IS NULL
  );

WITH users_missing_primary AS (
  SELECT ue.user_id
  FROM public.user_email_addresses ue
  WHERE ue.deleted_at IS NULL
  GROUP BY ue.user_id
  HAVING bool_or(ue.is_primary) = false
), ranked_active_emails AS (
  SELECT
    ue.id,
    ue.user_id,
    row_number() OVER (
      PARTITION BY ue.user_id
      ORDER BY ue.created_at ASC, ue.id ASC
    ) AS primary_rank
  FROM public.user_email_addresses ue
  JOIN users_missing_primary missing
    ON missing.user_id = ue.user_id
  WHERE ue.deleted_at IS NULL
)
UPDATE public.user_email_addresses ue
SET
  is_primary = true,
  updated_at = now()
FROM ranked_active_emails ranked
WHERE ue.id = ranked.id
  AND ranked.primary_rank = 1;

CREATE OR REPLACE FUNCTION public.sync_users_primary_email_from_history()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
  target_user_id bigint;
BEGIN
  target_user_id := COALESCE(NEW.user_id, OLD.user_id);

  UPDATE public.users u
  SET
    email = next_email.email,
    updated_at = now()
  FROM (
    SELECT ue.email
    FROM public.user_email_addresses ue
    WHERE ue.user_id = target_user_id
      AND ue.deleted_at IS NULL
    ORDER BY ue.is_primary DESC, ue.created_at ASC, ue.id ASC
    LIMIT 1
  ) AS next_email
  WHERE u.id = target_user_id
    AND u.email IS DISTINCT FROM next_email.email;

  UPDATE public.users
  SET
    email = NULL,
    updated_at = now()
  WHERE id = target_user_id
    AND NOT EXISTS (
      SELECT 1
      FROM public.user_email_addresses ue
      WHERE ue.user_id = target_user_id
        AND ue.deleted_at IS NULL
    )
    AND email IS NOT NULL;

  RETURN COALESCE(NEW, OLD);
END;
$$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_trigger
    WHERE tgname = 'sync_users_primary_email_from_history_trigger'
      AND tgrelid = 'public.user_email_addresses'::regclass
  ) THEN
    CREATE TRIGGER sync_users_primary_email_from_history_trigger
    AFTER INSERT OR UPDATE OR DELETE ON public.user_email_addresses
    FOR EACH ROW
    EXECUTE FUNCTION public.sync_users_primary_email_from_history();
  END IF;
END
$$;

UPDATE public.users u
SET
  email = next_email.email,
  updated_at = now()
FROM (
  SELECT DISTINCT ON (ue.user_id)
    ue.user_id,
    ue.email
  FROM public.user_email_addresses ue
  WHERE ue.deleted_at IS NULL
  ORDER BY ue.user_id, ue.is_primary DESC, ue.created_at ASC, ue.id ASC
) AS next_email
WHERE u.id = next_email.user_id
  AND u.email IS DISTINCT FROM next_email.email;

COMMIT;

-- DOWN
-- BEGIN;
-- DROP TRIGGER IF EXISTS sync_users_primary_email_from_history_trigger ON public.user_email_addresses;
-- DROP FUNCTION IF EXISTS public.sync_users_primary_email_from_history();
-- DROP INDEX IF EXISTS public.user_email_addresses_active_user_id_idx;
-- DROP INDEX IF EXISTS public.user_email_addresses_active_primary_per_user_key;
-- DROP INDEX IF EXISTS public.user_email_addresses_active_email_key;
-- DROP TABLE IF EXISTS public.user_email_addresses;
-- COMMIT;
