-- migrate:up
BEGIN;

CREATE TABLE IF NOT EXISTS public.ref_apps (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug text NOT NULL,
  name text NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT ref_apps_slug_key UNIQUE (slug)
);

CREATE TABLE IF NOT EXISTS public.ref_citycoins (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug text NOT NULL,
  display_name text NOT NULL,
  symbol text NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT ref_citycoins_slug_key UNIQUE (slug)
);

CREATE TABLE IF NOT EXISTS public.ref_app_instances (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug text NOT NULL,
  app_id bigint NOT NULL REFERENCES public.ref_apps(id) ON DELETE CASCADE,
  citycoin_id bigint NOT NULL REFERENCES public.ref_citycoins(id) ON DELETE CASCADE,
  environment text NOT NULL DEFAULT 'development',
  site_url text,
  supabase_project_ref text,
  supabase_url text,
  notes text,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT ref_app_instances_slug_key UNIQUE (slug),
  CONSTRAINT ref_app_instances_app_city_env_key UNIQUE (app_id, citycoin_id, environment)
);

INSERT INTO public.ref_apps (slug, name)
VALUES
  ('wallet', 'Wallet'),
  ('sparechange', 'Spare Change')
ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name;

INSERT INTO public.ref_citycoins (slug, display_name, symbol)
VALUES ('tcoin', 'Toronto Coin', 'TCOIN')
ON CONFLICT (slug) DO UPDATE SET display_name = EXCLUDED.display_name, symbol = EXCLUDED.symbol;

WITH app_rows AS (
  SELECT id, slug FROM public.ref_apps WHERE slug IN ('wallet', 'sparechange')
),
city_row AS (
  SELECT id FROM public.ref_citycoins WHERE slug = 'tcoin'
),
requested_envs AS (
  SELECT * FROM (VALUES ('development'), ('staging'), ('production')) AS env(environment)
)
INSERT INTO public.ref_app_instances (slug, app_id, citycoin_id, environment, site_url, supabase_project_ref, supabase_url, notes)
SELECT
  app.slug || '-' || 'tcoin' || '-' || env.environment AS slug,
  app.id,
  city_row.id,
  env.environment,
  CASE
    WHEN env.environment = 'development' THEN 'http://localhost:3000'
    WHEN env.environment = 'staging' THEN NULL
    WHEN env.environment = 'production' THEN NULL
    ELSE NULL
  END AS site_url,
  NULL AS supabase_project_ref,
  NULL AS supabase_url,
  NULL AS notes
FROM app_rows AS app
CROSS JOIN city_row
CROSS JOIN requested_envs AS env
ON CONFLICT (slug) DO UPDATE
SET
  app_id = EXCLUDED.app_id,
  citycoin_id = EXCLUDED.citycoin_id,
  environment = EXCLUDED.environment,
  site_url = EXCLUDED.site_url,
  supabase_project_ref = EXCLUDED.supabase_project_ref,
  supabase_url = EXCLUDED.supabase_url,
  notes = EXCLUDED.notes;

COMMIT;

-- migrate:down
BEGIN;

DELETE FROM public.ref_app_instances
WHERE slug IN (
  'wallet-tcoin-development',
  'wallet-tcoin-staging',
  'wallet-tcoin-production',
  'sparechange-tcoin-development',
  'sparechange-tcoin-staging',
  'sparechange-tcoin-production'
);

DELETE FROM public.ref_apps WHERE slug IN ('wallet', 'sparechange');
DELETE FROM public.ref_citycoins WHERE slug = 'tcoin';

DROP TABLE IF EXISTS public.ref_app_instances;
DROP TABLE IF EXISTS public.ref_citycoins;
DROP TABLE IF EXISTS public.ref_apps;

COMMIT;
