-- v1.14: enforce unique auth ownership, canonicalize phone ownership history, and prepare multi-auth contact attachment.

BEGIN;

CREATE TABLE IF NOT EXISTS public._migration_v1_14_duplicate_auth_user_ids_backup (
  user_id bigint PRIMARY KEY REFERENCES public.users(id) ON DELETE CASCADE,
  auth_user_id text NOT NULL,
  email text,
  phone text,
  captured_at timestamptz NOT NULL DEFAULT timezone('utc', now())
);

CREATE TABLE IF NOT EXISTS public._migration_v1_14_duplicate_user_phones_backup (
  user_id bigint PRIMARY KEY REFERENCES public.users(id) ON DELETE CASCADE,
  phone text NOT NULL,
  captured_at timestamptz NOT NULL DEFAULT timezone('utc', now())
);

WITH ranked_auth_rows AS (
  SELECT
    u.id,
    u.auth_user_id,
    u.email,
    u.phone,
    row_number() OVER (
      PARTITION BY u.auth_user_id
      ORDER BY u.created_at ASC NULLS LAST, u.id ASC
    ) AS auth_rank
  FROM public.users AS u
  WHERE u.auth_user_id IS NOT NULL
)
INSERT INTO public._migration_v1_14_duplicate_auth_user_ids_backup (user_id, auth_user_id, email, phone, captured_at)
SELECT
  ranked_auth_rows.id,
  ranked_auth_rows.auth_user_id,
  ranked_auth_rows.email,
  ranked_auth_rows.phone,
  timezone('utc', now())
FROM ranked_auth_rows
WHERE ranked_auth_rows.auth_rank > 1
ON CONFLICT (user_id) DO UPDATE
SET auth_user_id = EXCLUDED.auth_user_id,
    email = EXCLUDED.email,
    phone = EXCLUDED.phone,
    captured_at = EXCLUDED.captured_at;

UPDATE public.users AS u
SET auth_user_id = NULL,
    updated_at = timezone('utc', now())
WHERE u.id IN (
  SELECT backup.user_id
  FROM public._migration_v1_14_duplicate_auth_user_ids_backup AS backup
);

CREATE UNIQUE INDEX IF NOT EXISTS users_auth_user_id_key
  ON public.users (auth_user_id)
  WHERE auth_user_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS public.user_phone_addresses (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  phone text NOT NULL,
  is_primary boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz
);

ALTER TABLE public.user_phone_addresses
  ADD COLUMN IF NOT EXISTS user_id bigint,
  ADD COLUMN IF NOT EXISTS phone text,
  ADD COLUMN IF NOT EXISTS is_primary boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS created_at timestamptz DEFAULT now(),
  ADD COLUMN IF NOT EXISTS updated_at timestamptz DEFAULT now(),
  ADD COLUMN IF NOT EXISTS deleted_at timestamptz;

UPDATE public.user_phone_addresses
SET
  phone = regexp_replace(btrim(phone), '\s+', '', 'g'),
  updated_at = COALESCE(updated_at, now()),
  created_at = COALESCE(created_at, now()),
  is_primary = COALESCE(is_primary, false)
WHERE phone IS NOT NULL
  AND (
    phone <> regexp_replace(btrim(phone), '\s+', '', 'g')
    OR updated_at IS NULL
    OR created_at IS NULL
    OR is_primary IS NULL
  );

CREATE UNIQUE INDEX IF NOT EXISTS user_phone_addresses_active_phone_key
  ON public.user_phone_addresses (phone)
  WHERE deleted_at IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS user_phone_addresses_active_primary_per_user_key
  ON public.user_phone_addresses (user_id)
  WHERE deleted_at IS NULL AND is_primary = true;

CREATE INDEX IF NOT EXISTS user_phone_addresses_active_user_id_idx
  ON public.user_phone_addresses (user_id, created_at)
  WHERE deleted_at IS NULL;

WITH ranked_user_phones AS (
  SELECT
    u.id AS user_id,
    regexp_replace(btrim(u.phone), '\s+', '', 'g') AS normalized_phone,
    u.created_at,
    row_number() OVER (
      PARTITION BY regexp_replace(btrim(u.phone), '\s+', '', 'g')
      ORDER BY u.created_at ASC NULLS LAST, u.id ASC
    ) AS phone_rank
  FROM public.users AS u
  WHERE u.phone IS NOT NULL
    AND btrim(u.phone) <> ''
),
duplicate_user_phones AS (
  SELECT
    ranked_user_phones.user_id,
    ranked_user_phones.normalized_phone
  FROM ranked_user_phones
  WHERE ranked_user_phones.phone_rank > 1
)
INSERT INTO public._migration_v1_14_duplicate_user_phones_backup (user_id, phone, captured_at)
SELECT
  duplicate_user_phones.user_id,
  duplicate_user_phones.normalized_phone,
  timezone('utc', now())
FROM duplicate_user_phones
ON CONFLICT (user_id) DO UPDATE
SET phone = EXCLUDED.phone,
    captured_at = EXCLUDED.captured_at;

WITH ranked_user_phones AS (
  SELECT
    u.id AS user_id,
    regexp_replace(btrim(u.phone), '\s+', '', 'g') AS normalized_phone,
    COALESCE(u.created_at, now()) AS created_at,
    COALESCE(u.updated_at, COALESCE(u.created_at, now())) AS updated_at,
    row_number() OVER (
      PARTITION BY regexp_replace(btrim(u.phone), '\s+', '', 'g')
      ORDER BY u.created_at ASC NULLS LAST, u.id ASC
    ) AS phone_rank
  FROM public.users AS u
  WHERE u.phone IS NOT NULL
    AND btrim(u.phone) <> ''
)
INSERT INTO public.user_phone_addresses (user_id, phone, is_primary, created_at, updated_at)
SELECT
  ranked_user_phones.user_id,
  ranked_user_phones.normalized_phone,
  true,
  ranked_user_phones.created_at,
  ranked_user_phones.updated_at
FROM ranked_user_phones
WHERE ranked_user_phones.phone_rank = 1
  AND NOT EXISTS (
    SELECT 1
    FROM public.user_phone_addresses up
    WHERE up.user_id = ranked_user_phones.user_id
      AND up.phone = ranked_user_phones.normalized_phone
      AND up.deleted_at IS NULL
  );

CREATE OR REPLACE FUNCTION public.sync_users_primary_phone_from_history()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
  target_user_id bigint;
BEGIN
  target_user_id := COALESCE(NEW.user_id, OLD.user_id);

  UPDATE public.users u
  SET
    phone = next_phone.phone,
    updated_at = now()
  FROM (
    SELECT up.phone
    FROM public.user_phone_addresses up
    WHERE up.user_id = target_user_id
      AND up.deleted_at IS NULL
    ORDER BY up.is_primary DESC, up.created_at ASC, up.id ASC
    LIMIT 1
  ) AS next_phone
  WHERE u.id = target_user_id
    AND u.phone IS DISTINCT FROM next_phone.phone;

  UPDATE public.users
  SET
    phone = NULL,
    updated_at = now()
  WHERE id = target_user_id
    AND NOT EXISTS (
      SELECT 1
      FROM public.user_phone_addresses up
      WHERE up.user_id = target_user_id
        AND up.deleted_at IS NULL
    )
    AND phone IS NOT NULL;

  RETURN COALESCE(NEW, OLD);
END;
$$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_trigger
    WHERE tgname = 'sync_users_primary_phone_from_history_trigger'
      AND tgrelid = 'public.user_phone_addresses'::regclass
  ) THEN
    CREATE TRIGGER sync_users_primary_phone_from_history_trigger
    AFTER INSERT OR UPDATE OR DELETE ON public.user_phone_addresses
    FOR EACH ROW
    EXECUTE FUNCTION public.sync_users_primary_phone_from_history();
  END IF;
END
$$;

UPDATE public.users u
SET
  phone = next_phone.phone,
  updated_at = now()
FROM (
  SELECT DISTINCT ON (up.user_id)
    up.user_id,
    up.phone
  FROM public.user_phone_addresses up
  WHERE up.deleted_at IS NULL
  ORDER BY up.user_id, up.is_primary DESC, up.created_at ASC, up.id ASC
) AS next_phone
WHERE u.id = next_phone.user_id
  AND u.phone IS DISTINCT FROM next_phone.phone;

UPDATE public.users
SET
  phone = NULL,
  updated_at = now()
WHERE id IN (
  SELECT backup.user_id
  FROM public._migration_v1_14_duplicate_user_phones_backup AS backup
)
  AND NOT EXISTS (
    SELECT 1
    FROM public.user_phone_addresses up
    WHERE up.user_id = users.id
      AND up.deleted_at IS NULL
  );

COMMIT;

-- DOWN
-- BEGIN;
-- DROP TRIGGER IF EXISTS sync_users_primary_phone_from_history_trigger ON public.user_phone_addresses;
-- DROP FUNCTION IF EXISTS public.sync_users_primary_phone_from_history();
-- DROP INDEX IF EXISTS public.user_phone_addresses_active_user_id_idx;
-- DROP INDEX IF EXISTS public.user_phone_addresses_active_primary_per_user_key;
-- DROP INDEX IF EXISTS public.user_phone_addresses_active_phone_key;
-- DROP TABLE IF EXISTS public.user_phone_addresses;
-- DROP INDEX IF EXISTS public.users_auth_user_id_key;
-- UPDATE public.users AS u
-- SET auth_user_id = backup.auth_user_id,
--     phone = COALESCE(phone_backup.phone, u.phone),
--     updated_at = timezone('utc', now())
-- FROM public._migration_v1_14_duplicate_auth_user_ids_backup AS backup
-- LEFT JOIN public._migration_v1_14_duplicate_user_phones_backup AS phone_backup
--   ON phone_backup.user_id = backup.user_id
-- WHERE backup.user_id = u.id;
-- UPDATE public.users AS u
-- SET phone = phone_backup.phone,
--     updated_at = timezone('utc', now())
-- FROM public._migration_v1_14_duplicate_user_phones_backup AS phone_backup
-- WHERE phone_backup.user_id = u.id;
-- DROP TABLE IF EXISTS public._migration_v1_14_duplicate_user_phones_backup;
-- DROP TABLE IF EXISTS public._migration_v1_14_duplicate_auth_user_ids_backup;
-- COMMIT;
