name: Supabase Deploy (DEV)

on:
  push:
    branches: [ dev ]
    paths:
      - "supabase/migrations/**"
  workflow_dispatch: {}

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    concurrency:
      group: deploy-dev
      cancel-in-progress: false
    steps:
      - uses: actions/checkout@v4
      - uses: supabase/setup-cli@v1
      - name: Apply migrations to DEV
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        run: supabase db push --project-ref ${{ secrets.SUPABASE_PROJECT_REF_DEV }}
