name: Supabase Pull Drift (select env → repo)

on:
  workflow_dispatch:
    inputs:
      target:
        type: choice
        description: Which environment to diff?
        default: DEV
        options: [DEV, PREVIEW, PROD]

jobs:
  pull-remote-changes:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
      - uses: supabase/setup-cli@v1

      - name: Ensure migrations folder
        run: |
          mkdir -p supabase/migrations
          ls -la supabase/migrations || true

      - name: Build DB URL for selected env
        id: makeurl
        env:
          INPUT_TARGET: ${{ github.event.inputs.target }}
          PROD_REF:     ${{ secrets.SUPABASE_PROJECT_REF_PROD }}
          PREVIEW_REF:  ${{ secrets.SUPABASE_PROJECT_REF_PREVIEW }}
          DEV_REF:      ${{ secrets.SUPABASE_PROJECT_REF_DEV }}
          PROD_PASS:    ${{ secrets.SUPABASE_DB_PASSWORD_PROD }}
          PREVIEW_PASS: ${{ secrets.SUPABASE_DB_PASSWORD_PREVIEW }}
          DEV_PASS:     ${{ secrets.SUPABASE_DB_PASSWORD_DEV }}
        run: |
          set -e
          pick_host () { echo "db.$1.supabase.co"; }
          case "$INPUT_TARGET" in
            PROD)   HOST=$(pick_host "$PROD_REF");   PASS="$PROD_PASS"   ;;
            PREVIEW)HOST=$(pick_host "$PREVIEW_REF");PASS="$PREVIEW_PASS";;
            DEV|*)  HOST=$(pick_host "$DEV_REF");    PASS="$DEV_PASS"    ;;
          esac
          ENC_PASS=$(node -e "process.stdout.write(encodeURIComponent(process.env.PASS || ''))")
          echo "DB_URL=postgresql://postgres:${ENC_PASS}@${HOST}:5432/postgres?sslmode=require" >> "$GITHUB_OUTPUT"
          echo "Using $HOST (password hidden)"

      - name: Generate drift migration
        id: diff
        run: |
          set -e
          ts=$(date -u +"%Y%m%d%H%M%S")
          out="supabase/migrations/${ts}_remote_drift.sql"
          supabase db diff \
            --db-url "${{ steps.makeurl.outputs.DB_URL }}" \
            --schema public \
            --schema storage \
            --schema auth \
            -f "$out" || true
          ls -la supabase/migrations || true
          if [ -s "$out" ]; then
            echo "has_changes=true" >> "$GITHUB_OUTPUT"
            echo "file=$out" >> "$GITHUB_OUTPUT"
            head -n 50 "$out" || true
          else
            rm -f "$out"
            echo "has_changes=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Open/Update PR with drift migration
        if: steps.diff.outputs.has_changes == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          title: "chore(db): sync ${{ github.event.inputs.target || 'DEV' }} schema drift"
          commit-message: "chore(db): add migration from ${{ github.event.inputs.target || 'DEV' }} live schema"
          branch: chore/db-remote-drift-${{ github.event.inputs.target || 'DEV' }}
          base: main
          add-paths: supabase/migrations/**
          body: |
            Generated by `supabase db diff` from ${{ github.event.inputs.target || 'DEV' }}.
            Schemas: public, storage, auth.
