name: db-pull

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 6 * * *"   # optional daily drift check at 06:00 UTC

jobs:
  pull-remote-changes:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: supabase/setup-cli@v1

      - name: Link to project
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        run: supabase link --project-ref ${{ secrets.SUPABASE_PROJECT_REF }}

      - name: Generate drift migration from remote
        id: diff
        run: |
          ts=$(date -u +"%Y%m%d%H%M%S")
          file="supabase/migrations/${ts}_remote_drift.sql"
          # Create migration comparing live DB to the migrations folder
          supabase db diff -f "$file" --linked || true

          if [ -s "$file" ]; then
            echo "has_changes=true" >> "$GITHUB_OUTPUT"
            echo "file=$file" >> "$GITHUB_OUTPUT"
          else
            rm -f "$file"
            echo "has_changes=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Create PR with drift migration
        if: steps.diff.outputs.has_changes == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          title: "chore(db): sync remote schema drift"
          commit-message: "chore(db): add migration generated from remote schema drift"
          branch: chore/db-remote-drift
          base: main
          body: |
            This PR was generated by `supabase db diff` against the live project.
            Review carefully. Merging will apply via db-push on main.
          add-paths: |
            supabase/migrations/**
