name: Supabase PR Migrations (Preview DB)

on:
  pull_request:
    types: [opened, synchronize, closed]
    paths:
      - "supabase/migrations/**"

jobs:
  preview-migrations:
    if: github.event.action != 'closed'
    name: Reset & apply to PREVIEW
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: supabase/setup-cli@v1

      - name: Build PREVIEW DB URL
        id: makeurl
        env:
          PREVIEW_REF:  ${{ secrets.SUPABASE_PROJECT_REF_PREVIEW }}
          PREVIEW_PASS: ${{ secrets.SUPABASE_DB_PASSWORD_PREVIEW }}
        run: |
          set -e
          HOST="db.${PREVIEW_REF}.supabase.co"
          ENC_PASS=$(node -e "process.stdout.write(encodeURIComponent(process.env.PREVIEW_PASS || ''))")
          echo "DB_URL=postgresql://postgres:${ENC_PASS}@${HOST}:5432/postgres?sslmode=require" >> "$GITHUB_OUTPUT"
          echo "Using host ${HOST} (password hidden)."

      - name: Reset preview DB to clean baseline
        run: supabase db reset --db-url "${{ steps.makeurl.outputs.DB_URL }}" --force

      - name: Apply PR migrations (up)
        run: supabase db push --db-url "${{ steps.makeurl.outputs.DB_URL }}"

  rollback-migrations:
    if: github.event.action == 'closed' && github.event.pull_request.merged == false
    name: Reset PREVIEW to main baseline on close (no merge)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
      - uses: supabase/setup-cli@v1

      - name: Build PREVIEW DB URL
        id: makeurl
        env:
          PREVIEW_REF:  ${{ secrets.SUPABASE_PROJECT_REF_PREVIEW }}
          PREVIEW_PASS: ${{ secrets.SUPABASE_DB_PASSWORD_PREVIEW }}
        run: |
          set -e
          HOST="db.${PREVIEW_REF}.supabase.co"
          ENC_PASS=$(node -e "process.stdout.write(encodeURIComponent(process.env.PREVIEW_PASS || ''))")
          echo "DB_URL=postgresql://postgres:${ENC_PASS}@${HOST}:5432/postgres?sslmode=require" >> "$GITHUB_OUTPUT"

      - name: Reset preview DB to main baseline
        run: supabase db reset --db-url "${{ steps.makeurl.outputs.DB_URL }}" --force
